// Generated by scripts/optimize-models.mjs - do not edit by hand.
//
// Every optimized model is named after a hash of its own contents, so a
// rebuilt car is served from a new URL and no visitor is left holding a stale
// copy of one (see next.config.ts, which caches /models/* for a year).
export const MODEL_URLS = {
  "porsche-718-gt4": "/models/porsche-718-gt4.fc23adbe.glb",
  "porsche-911-carrera-4s": "/models/porsche-911-carrera-4s.b03748f0.glb",
  "porsche-917k-lm": "/models/porsche-917k-lm.c8567dbb.glb",
  "porsche-918-spyder": "/models/porsche-918-spyder.92e593f4.glb",
  "porsche-930-turbo": "/models/porsche-930-turbo.079be1c5.glb",
  "porsche-gt3-rs": "/models/porsche-gt3-rs.fda7a94a.glb",
  "porsche-mission-r": "/models/porsche-mission-r.276651fd.glb",
} as const;
