// Generated by scripts/extract-particle-points.mjs - do not edit by hand.
//
// The binary file is a flat Float32Array, 10 floats per particle interleaved
// as [x, y, z, dx, dy, dz, r, g, b, seed] - assembled position (world-space
// meters), dispersed/scattered position, linear 0-1 color, and a 0-1 wobble
// seed. Both positions are baked at build time so the runtime never runs a
// per-particle scatter computation. Named after a hash of its own bytes so a
// rebuilt cloud is never served stale from a returning visitor's cache (see
// next.config.ts).
export const PARTICLE_POINTS = {
  url: "/particles/gt3rs-points.026b0620.bin",
  count: 40946,
  bounds: {
    min: [-1.014, -0.084, -2.360],
    max: [1.015, 1.319, 2.209],
  },
} as const;
