// Generated by scripts/capture-fleet-images.mjs — do not edit by hand.
export const SILHOUETTE_IMAGES: Record<string, string> = {
  "917k-lm": "/silhouettes/917k-lm.67164c78.png",
  "930-turbo": "/silhouettes/930-turbo.a38792a0.png",
  "918-spyder": "/silhouettes/918-spyder.671194b7.png",
  "911-carrera-4s": "/silhouettes/911-carrera-4s.0a1601ba.png",
  "718-gt4": "/silhouettes/718-gt4.79508aef.png",
  "mission-r": "/silhouettes/mission-r.104acc00.png",
  gt3rs: "/silhouettes/gt3rs.e6171e1a.png",
};
