// Generated by scripts/capture-fleet-images.mjs — do not edit by hand.
export const SILHOUETTE_IMAGES: Record<string, string> = {
  "917k-lm": "/silhouettes/917k-lm.f0d16aea.webp",
  "930-turbo": "/silhouettes/930-turbo.74f77167.webp",
  "918-spyder": "/silhouettes/918-spyder.b54bc2d8.webp",
  "911-carrera-4s": "/silhouettes/911-carrera-4s.8d892f63.webp",
  "718-gt4": "/silhouettes/718-gt4.d0e21829.webp",
  "mission-r": "/silhouettes/mission-r.cc1d6ef3.webp",
  gt3rs: "/silhouettes/gt3rs.e0288f71.webp",
};
